event_index:
    path:     /event
    defaults: { _controller: "EventBundle:Event:index" }
    methods:  GET

event_index_user:
    path:     /
    defaults: { _controller: "EventBundle:Event:index_user" }
    methods:  GET

event_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EventBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }
    methods:  [GET, POST]
    
event_update:
    path:     /{id}/update
    defaults: { _controller: "EventBundle:Event:update" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    methods:  DELETE
